name: Docker

on: [push,pull_request]

jobs:
  docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        uses: docker/setup-buildx-action@v1
        id: builder-prod
      -
        uses: docker/setup-buildx-action@v1
        id: builder-dev
      -
        name: Cache Docker layers Dev
        uses: actions/cache@v2.1.4
        with:
          path: /tmp/.buildx-cache-dev
          key: ${{ runner.os }}-buildx-dev-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-dev-
      -
        name: Build Dev Image
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.builder-dev.outputs.name }}
          context: .
          file: Dockerfile.dev
          tags: joel/weblog:dev
          cache-from: type=local,src=/tmp/.buildx-cache-dev
          cache-to: type=local,dest=/tmp/.buildx-cache-dev-new
      -
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move dev cache
        run: |
          rm -rf /tmp/.buildx-cache-dev
          mv /tmp/.buildx-cache-dev-new /tmp/.buildx-cache-dev
      -
        name: Cache Docker layers Prod
        uses: actions/cache@v2.1.4
        with:
          path: /tmp/.buildx-cache-prod
          key: ${{ runner.os }}-buildx-prod-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-prod-
      -
        name: Build Prod Image
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.builder-prod.outputs.name }}
          context: .
          tags: joel/weblog:prod
          cache-from: type=local,src=/tmp/.buildx-cache-prod
          cache-to: type=local,dest=/tmp/.buildx-cache-prod-new
      -
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move prod cache
        run: |
          rm -rf /tmp/.buildx-cache-prod
          mv /tmp/.buildx-cache-prod-new /tmp/.buildx-cache-prod